[package]
name = "climate"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "practical command-line interfaces"
license = "Apache-2.0"
homepage = "https://github.com/spacejam/climate"
keywords = ["cli", "commandline", "visualization", "ui"]

[[test]]

name = "test"
path = "test/test.rs"

[dependencies]
termion = "1.0"
quickcheck = "0.3"
log = "0.3"
lazy_static = "0.2"
